# Generated by Django 4.0.6 on 2022-08-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('time_meter', models.CharField(max_length=254)),
                ('schedule', models.CharField(max_length=254)),
                ('type_obs', models.CharField(max_length=254)),
                ('expected_d', models.IntegerField(null=True)),
                ('expected_m', models.IntegerField(null=True)),
                ('expected_s', models.IntegerField(null=True)),
                ('expected_y', models.IntegerField(null=True)),
                ('delay_1t', models.IntegerField(null=True)),
                ('delay_2t', models.IntegerField(null=True)),
                ('delay_3t', models.IntegerField(null=True)),
            ],
        ),
    ]
