# Generated by Django 4.0.6 on 2022-09-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='expected_d',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='production',
            name='expected_m',
        ),
        migrations.RemoveField(
            model_name='production',
            name='expected_s',
        ),
        migrations.RemoveField(
            model_name='production',
            name='expected_y',
        ),
        migrations.RemoveField(
            model_name='production',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='production',
            name='time_meter',
        ),
        migrations.AddField(
            model_name='production',
            name='end_t',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='start_t',
            field=models.TimeField(null=True),
        ),
    ]
