# Generated by Django 4.0.6 on 2022-09-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_rename_expected_d_production_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='delay_3t',
        ),
    ]
