# Generated by Django 4.0.6 on 2022-09-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_production_full_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='production',
            name='type_obs',
            field=models.CharField(max_length=20),
        ),
    ]
