# Generated by Django 4.0.6 on 2022-08-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OACI', models.CharField(max_length=50)),
                ('OMM', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('longitude', models.FloatField(max_length=100)),
                ('latitude', models.FloatField(max_length=100)),
                ('altitude', models.FloatField(max_length=100)),
            ],
        ),
    ]
