# Generated by Django 4.0.6 on 2022-09-04 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_production_delay_3t'),
        ('stations', '0002_station_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='metar',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='metar', to='production.production'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='synop',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='synop', to='production.production'),
            preserve_default=False,
        ),
    ]
