# Generated by Django 4.0.6 on 2022-08-31 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_station_region'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station_Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='production.production')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='stations.station')),
            ],
        ),
    ]
