# Generated by Django 4.0.6 on 2022-09-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station_production',
            name='production',
        ),
        migrations.RemoveField(
            model_name='station_production',
            name='station',
        ),
    ]
