# Generated by Django 4.0.6 on 2022-08-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_date', models.DateTimeField(editable=False)),
                ('rec_date', models.DateTimeField(editable=False)),
                ('type', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=254)),
            ],
        ),
    ]
