# Generated by Django 4.0.6 on 2022-09-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0004_alter_station_metar_alter_station_synop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_date', models.DateField()),
                ('obs_time', models.TimeField()),
                ('rec_date', models.DateField(auto_now_add=True)),
                ('rec_time', models.TimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=254)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='stations.station')),
            ],
        ),
    ]
