# Generated by Django 4.0.6 on 2022-08-30 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_region'),
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='station',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='station', to='stations.station'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='rec_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
