# Generated by Django 4.0.6 on 2022-09-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='rec_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='rec_time',
            field=models.TimeField(),
        ),
    ]
