# Generated by Django 4.0.6 on 2022-09-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0002_alter_observation_rec_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
